CarrascoLanches/Areas/Admin/Controllers/AdminImagensController.cs
using CarrascoLanches.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;


namespace CarrascoLanches.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminImagensController : Controller
    {
        private readonly ConfigurationImagens _myConfig;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public AdminImagensController(IWebHostEnvironment hostingEnvironment,
            IOptions<ConfigurationImagens> myConfig)
        {
            _hostingEnvironment = hostingEnvironment; 
            _myConfig = myConfig.Value;
            
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> UploadFiles(List<IFormFile> files)
        {
            if (files == null || files.Count == 0)
            {
                ViewData["Erro"] = "Error: Arquivo(s) não selecionado(s)";
                return View(ViewData);
            }
            if (files.Count > 10)
            {
                ViewData["Erro"] = "Error: Quantidade de arquivos excedeu o limite";
                return View(ViewData);
            }

            long size = files.Sum(f => f.Length);
            var filePathsName = new List<string>();
            var filePath = Path.Combine(_hostingEnvironment.WebRootPath,
                _myConfig.NomePastaImagensProdutos);

            foreach (var formFile in files)
            {
                if (formFile.FileName.Contains(".jpg")|| formFile.FileName.Contains(".gif")
                    || formFile.FileName.Contains(".png"))
                {
                    var fileNameWithPath = string.Concat(filePath, "\\", formFile.FileName);
                    
                    filePathsName.Add(fileNameWithPath);

                    using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }
            ViewData["Resultado"] = $"{files.Count} arquivos foram enviados ao servidor, " +
                $"com tamanho total de: {size} bytes";

            ViewBag.Arquivos = filePathsName;
            
            return View(ViewData);

        }
        public IActionResult GetImagens()
        {
            FileManagerModel model = new FileManagerModel();

            var userImagesPath = Path.Combine(_hostingEnvironment.WebRootPath,
                _myConfig.NomePastaImagensProdutos);
            
            DirectoryInfo dir = new DirectoryInfo(userImagesPath);

            FileInfo[] files = dir.GetFiles();

            model.PathImagesProduto = _myConfig.NomePastaImagensProdutos;

            if (files.Length == 0)
            {
                ViewData["Erro"] = $"Nenhum arquivo encontrado na pasta {userImagesPath}";

            }

            model.Files = files;

            return View(model);
        }
        public IActionResult DeleteFile(string fname)
        {
            string _imagemDeleta = Path.Combine(_hostingEnvironment.WebRootPath,
                _myConfig.NomePastaImagensProdutos + "\\",fname);

            if (System.IO.File.Exists(_imagemDeleta))
            {
                System.IO.File.Delete(_imagemDeleta);

                ViewData["Deletado"] = $"Arquivo(s) {_imagemDeleta} deletado com sucesso";

            }
            return View("index");
        }
    }
}

CarrascoLanches/Areas/Admin/Views/AdminImagens/GetImagens.cshtml
@model FileManagerModel
@{
    ViewBag.Title = "Arquivos";
}

@if (Model.Files != null)
{
    <h3>Imagens:</h3>
    <hr />
    var caminho = Model.PathImagesProduto;
    <div class="row">
        @foreach  (FileInfo file in Model.Files)
        {
            <div class="column">
                <img src="~/@caminho/@file.Name" title="@file.Name" asp-append-version="true" width="125" height="125">
                <div style="padding:10px;text-align:left">
                    <a href="@Url.Action("DeleteFile","AdminImagens",new {fname=file.Name})">Excluir</a>
                </div>
            </div>
        }
    </div>
}

CarrascoLanches/Areas/Admin/Views/AdminImagens/Index.cshtml
<br />
<h4><strong>Gerenciar Imagens</strong></h4>
<br />
<table border="0" width="100%">
    <tr>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImagens" asp-action="UploadFiles">
                <img src="~/images/upload2.png" width="200" height="150" />
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><b>Selecione um ou mais arquivos para enviar :</b></p>
                        <p>(Arquivos com o mesmo nome serão sobrescritos)</p>
                        <input type="file" name="files" multiple class="button btn-outline-primary" />
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Enviar Arquivo(s)" class="button btn-outline-primary" />
                    </div>
                </div>
            </form>
        </td>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImagens" asp-action="GetImagens">
                <img src="~/images/visualizar1.jpg" width="200" height="200" />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><strong>Visualizar Imagens na pasta do servidor :</strong></p>
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Visualizar Arquivos no servidor" class="button btn-outline-warning" />
                    </div>
                </div>
            </form>
        </td>
    </tr>
</table>
<div class="container">
    @if (ViewData["Deletado"] != null)
    {
        <li>@ViewData["Deletado"]</li>
    }
</div>

CarrascoLanches/Areas/Admin/Views/AdminImagens/UploadFiles.cshtml
@{
    ViewData["Title"] = "UploadFiles";
}

<img src="~/images/upload2.png" width="200" height="150" />

<hr />

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        @if (ViewData["Erro"] != null)
        {
            <img src="~/images/erro1.png" width="150" height="150" />
            <h4>@ViewData["Erro"]</h4>
        }
    </div>

    <div class="container">
        @if (ViewData["Resultado"] != null)
        {
            <h4>@ViewData["Resultado"]</h4>
            <hr />
            @if (ViewBag.Arquivos != null)
            {
                @foreach (string arquivo in ViewBag.Arquivos)
                {
                    <li>
                        @arquivo
                    </li>
                }
            }
        }
    </div>
</div>